#!/bin/sh

echo Local File is "$1"
echo Pseudo file name is "$2"

MOVIE_PLAYER='mplayer -vo sdl'

case "$2" in
    *.avi | *.mpg | *.mpeg | *.divx  | *.AVI | *.MPG | *.MPEG | *.DIVX | *.ogm | *.OGM )
   $MOVIE_PLAYER  $1 &;;
 *) echo No player for this file;;
esac
